---
dependency:
  name: galaxy
driver:
  name: ec2
lint:
  name: yamllint
platforms:
  - name: instance
    image: ami-a1d349c0
    instance_type: t2.micro
    count: 1
    vpc_subnet_id: subnet-9ec280fa
    Type: "Test_Type"
    Function: "Test_Function"
    Zone: "Presentation"
provisioner:
  name: ansible
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  lint:
    name: flake8
